---
## Update APT configuration
#- name: add universe repository
#  register: universe_result
#  sudo: yes
#  apt_repository: >
#    repo="deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename|lower}} universe"
#    state=present
#
## Download keys and package lists
#- name: apt-get update
#  apt: update_cache=yes cache_valid_time=0
#  sudo: yes
#  when: universe_result.changed

- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes

- name: install gdebi
  apt: name=gdebi
  sudo: yes

- name: Check if vagrant is installed
  command: dpkg-query -W vagrant
  register: check_vagrant
  failed_when: false
  changed_when: false

- name: Download Ubuntu vagrant package
  command: wget -O /tmp/vagrant.deb {{vagrant_url}}
  args:
    creates: "/tmp/vagrant.deb"
  when: check_vagrant.rc == 1

- name: Install vagrant package
  sudo: true
  command: gdebi --non-interactive /tmp/vagrant.deb
  when: check_vagrant.rc == 1
